---

- name: Include all variable files
  include_vars:
    dir: 'vars' #change directory if needed
    extensions:
- yml

- name: Add ESXi Host to VCSA
  local_action:
            module: vmware_host
            validate_certs: false
            hostname: "{{ hostname }}"
            username: "{{ user_name }}"
            password: "{{ password }}"
            datacenter_name: Synergy_Poc
            cluster_name: Synergy_Poc_Cluster
            esxi_hostname: "{{ esxi_host }}"
            esxi_username: "{{ esxi_username }}"
            esxi_password: "{{ esxi_password }}"
            state: present
